file_format: "1"
id: hillside52
name: Hillside52
type: shield
url: https://github.com/mmccoyd/hillside/
requires: [pro_micro]
exposes: [i2c_oled]
features:
  - keys
  - display
  - studio
siblings:
  - hillside52_left
  - hillside52_right
